# Generated by Django 6.0.3 on 2026-03-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_tarefa_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="data_conclusao",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Conclusão"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Prazo"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="descricao",
            field=models.TextField(verbose_name="Descrição da tarefa"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Título da tarefa"),
        ),
    ]
