# Generated by Django 6.0.3 on 2026-03-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_tarefa_data_conclusao_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarefa",
            options={"ordering": ["deadline"]},
        ),
    ]
